<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.42460017 0.91895603 0.91888589 ... 0.91327385 0.42437794 0.42671888]
 [0.51772649 0.60807333 0.02824004 ... 0.77748615 0.58597281 0.98159576]
 [0.03604284 0.78446867 0.50565221 ... 0.40293169 0.66853765 0.05712658]
 ...
 [0.98163203 0.84852202 0.01521853 ... 0.80919339 0.74225738 0.23067815]
 [0.97605608 0.50105955 0.10893235 ... 0.45983084 0.95544992 0.01175399]
 [0.12916185 0.66755563 0.04835485 ... 0.81226891 0.07457417 0.90307254]]
[[0.42300875 0.34683428 0.26306428 ... 0.13233081 0.719366   0.27186944]
 [0.56517386 0.92800469 0.54056347 ... 0.7781718  0.43465391 0.53308781]
 [0.79178093 0.24825712 0.24563821 ... 0.88850422 0.56140685 0.75083889]
 ...
 [0.80939953 0.97210537 0.01963927 ... 0.66804866 0.54525321 0.23903888]
 [0.22944107 0.6477693  0.10584775 ... 0.28132321 0.58094387 0.63920479]
 [0.89564137 0.06121    0.48655584 ... 0.20455503 0.44288735 0.78125425]]


In [6]:
def mult(a, b):
    rez = []
    for i in range(len(a)):
        x = a[i]
        rez0 = []
        for j in range(len(b[i])):
            y = [b[m][j] for m in range(len(b))]
            rez0.append(sum([x[k] * y[k] for k in range(len(x))]))
        rez.append(rez0)
    return rez
            

In [4]:
def np_mult(a, b):
    return np.dot(a, b)

In [7]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 664 ms


In [5]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 17 ms


In [8]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3486101124726702e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [9]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.72876188 0.74482508 0.64258135] [0.14392812 0.62845284 0.19429336]


In [10]:
def no_numpy_scalar(v1, v2):
    return sum([v1[i] * v2[i] for i in range(len(v1))])

In [13]:
def numpy_scalar(v1, v2):
    return np.dot(v1, v2)

In [16]:
%time product_1 = no_numpy_scalar(a,b)
%time product_2 = numpy_scalar(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 0 ns


0.0

In [18]:
%%time
product_1 = numpy_scalar(a,b)

Wall time: 0 ns


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [19]:
# функция, решающая задачу с помощью NumPy
def diag_2k(a):
    d = a.diagonal()
    return sum([i for i in d if i % 2 == 0])

In [20]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 5, 1, 1, 5],
       [3, 6, 1, 6, 6],
       [8, 3, 5, 9, 2],
       [6, 1, 1, 9, 9],
       [9, 5, 3, 6, 2]])

In [21]:
%%time
# засечем время работы функции с NumPy
diag_2k(a)

Wall time: 17 ms


10

### Задание 4
​
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$, s_k=x_1+...+x_k, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.


​

​ 

In [22]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    return np.cumsum(A, axis=1)

In [23]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

NameError: name 'np_sec_av' is not defined

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [28]:
# функция, решающая задачу с помощью NumPy
from copy import copy


def transform(X, a=1):
    X1 = copy(X)
    for string in X:
        for i in range(len(string)):
            if i % 2 == 0:
                string[i] = string[i]**3
            else:
                string[i] = a
        string = string[-1]
        
    return np.hstack((X1, X))

In [29]:
X = np.array([i for i in range(1, 10, 2)])
print(transform(X))

TypeError: object of type 'numpy.int32' has no len()

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    #YOUR CODE

In [ ]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)